Kernel360/f1-KernelSquare-frontend

README.md

- CD를 위한 github action workflow의 동작을 확인하기 위한 pull request입니다.

chore: CD 테스트를 위한 readme.md 수정

---

README.md

> workflow에 aws credentials Permission 정보를 추가하였습니다.

fix: workflow에 aws credentials 허가 정보 추가

---

.github/workflows/cd-workflow.yml

fix: cd 관련 workflow 파일 수정

---

.github/workflows/cd-workflow.yml

> cd workflow에 aws region 관련 환경 변수 관련 사항을 반영하였습니다.

fix: cd workflow 환경 변수 수정 사항 반영

---

.github/workflows/cd-workflow.yml

> 버전 이슈 해결을 위해 aws-credentials의 버전을 수정하였습니다.

fix aws-credentials 버전 수정

---

.github/workflows/cd-workflow.yml

> cd workflow 파일에 checkout과 관련된 코드를 추가하였습니다.

fix: cd workflow checkout 관련 코드 추가

---

.github/workflows/cd-workflow.yml

> 기존 `PULL_REQUEST` 액션에서 외부 레포지토리에서 포크된 현재 상황에서의 CD를 가능하게 하는 `PULL_REQUEST_TARGET`으로 github action으로 수정하였습니다.

fix: github actions 수정 

---

.github/workflows/cd-workflow.yml

> cd workflow에서 레포지토리 관련 조건식을 삭제하였습니다.

chore: cd workflow 관련 조건문 삭제 

---

.github/workflows/cd-workflow.yml

> github action workflow에 node.js의 version 설정을 위한 코드를 추가하였습니다.

fix: node version 관련 설정 추가 

---

.github/workflows/cd-workflow.yml

> node.js의 version 명시와 관련된 코드를 수정하였습니다.

fix: node version 관련 코드 수정 

---

.github/workflows/cd-workflow.yml

> Public IP 관련 action을 변경하였습니다.

fix: Public IP 관련 action 변경

---

.github/workflows/cd-workflow.yml

> github actions에서 ec2 인증 방식을 변경하여 이미지 업로드 관련 오류를 해결하였습니다.

fix: github actions ec2 인증 방식 변경

---

.github/workflows/cd-workflow.yml

> slack notification이 항상 실행되도록 설정을 변경하였습니다.

fix: slack notification 설정 변경 

---

.github/workflows/cd-workflow.yml
.github/workflows/ci-workflow.yml

> CI/CD가 적절한 레포지토리에서 동작할 수 있도록 제한 조건을 추가하였습니다.

feat: CI/CD workflow 레포 제한 추가 

---

.github/workflows/cd-workflow.yml
.github/workflows/ci-workflow.yml

> github repository 이름을 명시하여 원하지 않는 skip 현상이 발생하지 않도록 하였습니다.

fix: github repository 이름 명시하도록 수정

---

src/page/coding-meetings/create/components/CustomMap/kakaoMap.tsx
src/page/coding-meetings/create/components/LocationSection.tsx

fix: 지도 좌표 오류 해결

---

src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx

popupStorage가 배열이 아닌경우 false로 초기화

popupStorage

---

src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
src/util/chat/popup.ts

팝업과 관련된 localStorage 에 예외 케이스 추가

localStorage 예외 케이스 추가

---

.github/workflows/dev-ci-workflow.yml
src/page/oauth/github/OAuthGithubSuccess.tsx
src/page/user-profile/components/UserProfilePresenter.tsx
src/page/user-profile/edit-nickname/form/SubmitStep.tsx

[#286](https://github.com/KernelSquare/Frontend/issues/286)
- 닉네임 수정 이후 유저 상태가 유지되도록 함
- 내 프로필 페이지인 경우에만 설정 버튼 노출

[fix] 닉네임 수정 관련 fix

---

src/app/coding-meetings/[token]/page.tsx
src/page/coding-meetings/util/cm-token.ts

> og
- [카카오 공유 디버거](https://developers.kakao.com/tool/debugger/sharing) 에서 Invalid URL 로 적용되지 않는 형식으로 수정 / 개발서버에서 선확인해보려고 함

[fix] 모각코 url 형식 수정(dev)

---

src/page/coding-meetings/detail/DetailPage.tsx
src/page/coding-meetings/util/cm-token.ts

> og
- 500 응답이 발생되지 않는 상황에서 모각코 상세 og 가 잘 적용되는지 보기 위함 (추측이 맞을 경우, 서버 렌더링에서도 에러가 없을 경우 200 응답일 것이며, 해당 상황에서는 정상적으로 og가 반영되어야 함)
- 렌더링은 되지만, 500에러가 콘솔에 확인되는 것이 서버 렌더링시 발생하는 localStorage 관련 에러로 추정되어 dynamic 으로 ssr 되지 않도록 수정
- 개발서버에 반영하여 보기 위함

[fix] 모각코 댓글 dynamic ssr false (dev)
